export const wilayat = [
  { name: "أدرار", number: 1, status: false },
  { name: "الشلف", number: 2, status: false },
  { name: "الأغواط", number: 3, status: false },
  { name: "أم البواقي", number: 4, status: false },
  { name: "باتنة", number: 5, status: false },
  { name: "بجاية", number: 6, status: false },
  { name: "بسكرة", number: 7, status: false },
  { name: "بشار", number: 8, status: false },
  { name: "البليدة", number: 9, status: false },
  { name: "البويرة", number: 10, status: false },
  { name: "تمنراست", number: 11, status: false },
  { name: "تبسة", number: 12, status: false },
  { name: "تلمسان", number: 13, status: false },
  { name: "تيارت", number: 14, status: false },
  { name: "تيزي وزو", number: 15, status: false },
  { name: "الجزائر", number: 16, status: false },
  { name: "الجلفة", number: 17, status: false },
  { name: "جيجل", number: 18, status: false },
  { name: "سطيف", number: 19, status: false },
  { name: "سعيدة", number: 20, status: false },
  { name: "سكيكدة", number: 21, status: false },
  { name: "سيدي بلعباس", number: 22, status: false },
  { name: "عنابة", number: 23, status: false },
  { name: "قالمة", number: 24, status: false },
  { name: "قسنطينة", number: 25, status: false },
  { name: "المدية", number: 26, status: false },
  { name: "مستغانم", number: 27, status: false },
  { name: "المسيلة", number: 28, status: false },
  { name: "معسكر", number: 29, status: false },
  { name: "ورقلة", number: 30, status: false },
  { name: "وهران", number: 31, status: false },
  { name: "البيض", number: 32, status: false },
  { name: "إليزي", number: 33, status: false },
  { name: "برج بوعريريج", number: 34, status: false },
  { name: "بومرداس", number: 35, status: false },
  { name: "الطارف", number: 36, status: false },
  { name: "تندوف", number: 37, status: false },
  { name: "تيسمسيلت", number: 38, status: false },
  { name: "الوادي", number: 39, status: false },
  { name: "خنشلة", number: 40, status: false },
  { name: "سوق أهراس", number: 41, status: false },
  { name: "تيبازة", number: 42, status: false },
  { name: "ميلة", number: 43, status: false },
  { name: "عين الدفلى", number: 44, status: false },
  { name: "النعامة", number: 45, status: false },
  { name: "عين تموشنت", number: 46, status: false },
  { name: "غرداية", number: 47, status: false },
  { name: "غليزان", number: 48, status: false },
  { name: "تيميمون", number: 49, status: false },
  { name: "برج باجي مختار", number: 50, status: false },
  { name: "أولاد جلال", number: 51, status: false },
  { name: "بني عباس", number: 52, status: false },
  { name: "إن صالح", number: 53, status: false },
  { name: "إن قزام", number: 54, status: false },
  { name: "توقرت", number: 55, status: false },
  { name: "جانت", number: 56, status: false },
  { name: "المغير", number: 57, status: false },
  { name: "المنيعة", number: 58, status: false },
];
